imports:
  - { resource: ./application.yaml }

services:
  Backoffice.Backend.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/elastic/ElasticEnvironmentArranger
    arguments: ['@Shared.ElasticConnectionManager', '@Backoffice.courses.ElasticConfig']
