services:
  Mooc.coursesCounter.CoursesCounterFinder:
    class: ../../../../../Contexts/Mooc/CoursesCounter/application/Find/CoursesCounterFinder
    arguments: ['@Mooc.coursesCounter.CoursesCounterRepository']

  Mooc.coursesCounter.CoursesCounterRepository:
    class: ../../../../../Contexts/Mooc/CoursesCounter/infrastructure/persistence/mongo/MongoCoursesCounterRepository
    arguments: ['@Shared.ConnectionManager']

  Mooc.coursesCounter.FindCoursesCounterQueryHandler:
    class: ../../../../../Contexts/Mooc/CoursesCounter/application/Find/FindCoursesCounterQueryHandler
    arguments: ['@Mooc.coursesCounter.CoursesCounterFinder']
    tags:
      - { name: 'queryHandler' }
