imports:
  - { resource: ./apps/application.yaml }
  - { resource: ./Courses/application.yaml }
  - { resource: ./CoursesCounter/application.yaml }
  - { resource: ./Notifications/application.yaml }
  - { resource: ./Shared/application.yaml }
